ifneq "$(MAKECMDGOALS)" "clean"
include ../../current/config/Makefile.include
endif

CPPFLAGS += -I../include

clean::
	rm -f *.o test core *.d $(EXTRA_CLEAN_TARGET)
	rm -rf Debug ii_files *.plg *.ilk
