TOPTESTDIR=..

ifneq "$(MAKECMDGOALS)" "clean"
include $(TOPTESTDIR)/../current/$(BUILDDIR)/config/Makefile.include
endif

CPPFLAGS += -I$(TOPTESTDIR)/include

clean::
	rm -f *.o test core *.d $(EXTRA_CLEAN_TARGET)
	rm -rf Debug ii_files *.plg *.ilk
