#include <vigra/accessor.hxx>
#include <vigra/array_vector.hxx>
#include <vigra/basicgeometry.hxx>
#include <vigra/basicimage.hxx>
#include <vigra/basicimageview.hxx>
#include <vigra/bordertreatment.hxx>
#include <vigra/boundarytensor.hxx>
#include <vigra/codec.hxx>
#include <vigra/colorconversions.hxx>
#include <vigra/combineimages.hxx>
#include <vigra/config.hxx>
#include <vigra/contourcirculator.hxx>
#include <vigra/convolution.hxx>
#include <vigra/copyimage.hxx>
#include <vigra/cornerdetection.hxx>
#include <vigra/diff2d.hxx>
#include <vigra/distancetransform.hxx>
#include <vigra/edgedetection.hxx>
#include <vigra/error.hxx>
#include <vigra/fftw3.hxx>
#include <vigra/flatmorphology.hxx>
#include <vigra/functorexpression.hxx>
#include <vigra/functortraits.hxx>
#include <vigra/gaborfilter.hxx>
#include <vigra/gaussians.hxx>
#include <vigra/imagecontainer.hxx>
#include <vigra/imageinfo.hxx>
#include <vigra/imageiterator.hxx>
#include <vigra/imageiteratoradapter.hxx>
#include <vigra/impex.hxx>
#include <vigra/initimage.hxx>
#include <vigra/inspectimage.hxx>
#include <vigra/interpolating_accessor.hxx>
#include <vigra/iteratoradapter.hxx>
#include <vigra/iteratortags.hxx>
#include <vigra/iteratortraits.hxx>
#include <vigra/labelimage.hxx>
#include <vigra/localminmax.hxx>
#include <vigra/mathutil.hxx>
#include <vigra/memory.hxx>
#include <vigra/metaprogramming.hxx>
#include <vigra/multi_array.hxx>
#include <vigra/multi_convolution.hxx>
#include <vigra/multi_impex.hxx>
#include <vigra/multi_iterator.hxx>
#include <vigra/multi_pointoperators.hxx>
#include <vigra/navigator.hxx>
#include <vigra/nonlineardiffusion.hxx>
#include <vigra/numerictraits.hxx>
#include <vigra/orientedtensorfilters.hxx>
#include <vigra/pixelneighborhood.hxx>
#include <vigra/polynomial.hxx>
#include <vigra/rational.hxx>
#include <vigra/recursiveconvolution.hxx>
#include <vigra/resampling_convolution.hxx>
#include <vigra/resizeimage.hxx>
#include <vigra/rgbvalue.hxx>
#include <vigra/seededregiongrowing.hxx>
#include <vigra/separableconvolution.hxx>
#include <vigra/splineimageview.hxx>
#include <vigra/splines.hxx>
#include <vigra/stdconvolution.hxx>
#include <vigra/stdimage.hxx>
#include <vigra/stdimagefunctions.hxx>
#include <vigra/symmetry.hxx>
#include <vigra/tensorutilities.hxx>
#include <vigra/tiff.hxx>
#include <vigra/tinyvector.hxx>
#include <vigra/transformimage.hxx>
#include <vigra/tuple.hxx>
#include <vigra/utilities.hxx>
int main() {}
